<?php

use Illuminate\Database\Seeder;

class CgDepartamentsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        DB::table('cg_departaments')->delete();
        
        DB::table('cg_departaments')->insert(array (
            0 => 
            array (
                'id' => 1,
                'enable' => 1,
                'icon' => '',
                'url_name_es' => 'modas',
                'name_es' => 'Modas',
                'title_es' => 'Moda PagoSpot',
                'description_es' => 'Te gusta comprar on line, mantente actualizado con las últimas tendencias y noticias de la moda y descubre una manera divertida de comprar!',
                'keywords_es' => 'Tienda, ofertas, moda, tendencias, Moda PagoSpot, comprar, divertida',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_name_en' => 'fashion',
                'name_en' => 'Fashion',
                'title_en' => 'Fashion PagoSpot',
                'description_en' => 'Like shopping online, our network of stores will keep you updated with the latest trends and fashion news. Come and discover a fun way to shop!',
                'keywords_en' => 'fashion, network stores, fun, shop, last trends, news',
                'url_img' => '',
                'color' => NULL,
                'created_at' => '2019-04-23 12:47:57',
                'updated_at' => '2019-04-23 12:48:31',
            ),
            1 => 
            array (
                'id' => 2,
                'enable' => 1,
                'icon' => '',
                'url_name_es' => 'relojes',
                'name_es' => 'Relojes',
                'title_es' => 'Relojes PagoSpot',
                'description_es' => 'El tiempo es importante para ti? Ven y consigue los modelos que se ajustan para ti de las mejores marcas.',
                'keywords_es' => 'tiempo, modelos, marcas, relojes',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_name_en' => 'watches',
                'name_en' => 'Watches',
                'title_en' => 'Watches PagoSpot',
                'description_en' => 'Time is important to you? Come and get the models that fit your style from the best brands.',
                'keywords_en' => 'watches, brand, style',
                'url_img' => '',
                'color' => NULL,
                'created_at' => '2019-04-23 12:47:57',
                'updated_at' => '2019-04-23 12:48:31',
            ),
            2 => 
            array (
                'id' => 3,
                'enable' => 1,
                'icon' => '',
                'url_name_es' => 'lentes',
                'name_es' => 'Lentes',
                'title_es' => 'Lentes PagoSpot',
                'description_es' => 'Un sin fin de modelos, marcas y accesorios para ti encuentra en los de tu preferencia y mira la vida desde otra perspectiva.',
                'keywords_es' => 'lentes, modelos, marcas, accesorios, mira, sol',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_name_en' => 'glasses',
                'name_en' => 'Glasses',
                'title_en' => 'Glasses PagoSpot',
                'description_en' => 'An endless number of models, brands and accessories for you. Find  the one ideal for your choice and look life from another perspective.',
                'keywords_en' => 'glasses, sunglasses, prescription, accesories, look',
                'url_img' => '',
                'color' => NULL,
                'created_at' => '2019-04-23 12:47:57',
                'updated_at' => '2019-04-23 12:48:31',
            ),
            3 => 
            array (
                'id' => 4,
                'enable' => 1,
                'icon' => '',
                'url_name_es' => 'joyeria',
                'name_es' => 'Joyeria',
                'title_es' => 'Joyería PagoSpot',
                'description_es' => 'Comprar joyas online nunca fue tan fácil, encuentra las mejores marcas y calidad con la mejor opción de precio. Ven y realiza tu oferta!',
                'keywords_es' => 'Joyería, joyas online, oferta',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_name_en' => 'jewelry',
                'name_en' => 'Jewelry',
                'title_en' => 'Jewelry PagoSpot',
                'description_en' => 'Buying jewelry online has never been easier, find the best brands and quality with the best price option. Come and make your offer!',
                'keywords_en' => 'jewelry, online offer',
                'url_img' => '',
                'color' => NULL,
                'created_at' => '2019-04-23 12:47:57',
                'updated_at' => '2019-04-23 12:48:31',
            ),
            4 => 
            array (
                'id' => 5,
                'enable' => 1,
                'icon' => '',
                'url_name_es' => 'accesorios',
                'name_es' => 'Accesorios',
                'title_es' => 'Accesorios PagoSpot',
                'description_es' => 'Porque no estas completo sin un accesorio adecuado, bolsos, collares, cinturones, aretes, pulceras; ven y encuentra el que necesitas.',
                'keywords_es' => 'accesorios, bolsos, collares, aretes, pulceras',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_name_en' => 'accessories',
                'name_en' => 'Accessories',
                'title_en' => 'Accessories PagoSpot',
                'description_en' => 'Because you are not complete without the right accessory, bags, necklaces, belts, earrings, bracelets; Come and find the one you need.',
                'keywords_en' => 'Accessories, bags, necklaces, belts, earrings, bracelets',
                'url_img' => '',
                'color' => NULL,
                'created_at' => '2019-04-23 12:47:57',
                'updated_at' => '2019-04-23 12:48:31',
            ),
            5 => 
            array (
                'id' => 6,
                'enable' => 1,
                'icon' => '',
                'url_name_es' => 'perfumes-y-fragancias',
                'name_es' => 'Perfumes y Fragancias',
                'title_es' => 'Perfumes y Fragancias PagoSpot',
                'description_es' => 'Las mejores fragancias y lociones originales para él y para ella de las mejores marcas 100% originales, con el mejor descuento para consentir a tu cuerpo.',
                'keywords_es' => 'Fragancias, perfumes, cuerpo, lociones',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_name_en' => 'parfumes-fragrances',
                'name_en' => 'Parfumes & fragrances',
                'title_en' => 'Parfumes & fragrances PagoSpot',
                'description_en' => 'Original fragrances and lotions for him and her. 100% original top brands with our best discounts to pamper your body.',
                'keywords_en' => 'original fragrances, lotions, body',
                'url_img' => '',
                'color' => NULL,
                'created_at' => '2019-04-23 12:47:57',
                'updated_at' => '2019-04-23 12:48:31',
            ),
            6 => 
            array (
                'id' => 7,
                'enable' => 1,
                'icon' => '',
                'url_name_es' => 'cuidado-personal',
                'name_es' => 'Cuidado Personal',
                'title_es' => 'Belleza Pagospot',
                'description_es' => 'Porque la belleza no sólo está en el ojo del observador, encuentra en nuestras tiendas todo lo que necesites para realzar tu bienestar.',
                'keywords_es' => 'belleza, bienestar',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_name_en' => 'personal-care',
                'name_en' => 'Personal Care',
                'title_en' => 'Beauty PagoSpot',
                'description_en' => 'Because beauty is not only in the eye of the beholder, in our stores find everything you need to enhance your wellbeing.',
                'keywords_en' => 'beauty, wellbeing',
                'url_img' => '',
                'color' => NULL,
                'created_at' => '2019-04-23 12:47:57',
                'updated_at' => '2019-04-23 12:48:31',
            ),
            7 => 
            array (
                'id' => 8,
                'enable' => 1,
                'icon' => '',
                'url_name_es' => 'salud',
                'name_es' => 'Salud',
                'title_es' => 'Salud y Cuidado Personal PagoSpot',
                'description_es' => 'En un mundo de constante actividad necesitamos cuidar más de nuestra salud y bienestar corporal. PagoSpot te ayuda a mantenerte en forma y jóven.',
                'keywords_es' => 'cuidado, salud, bienestar corporal, joven',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_name_en' => 'health',
                'name_en' => 'Health',
                'title_en' => 'Health & Personal Care PagoSpot',
                'description_en' => 'In our active world we need to take care of our health and well-being for it PagoSpot help you to find the product to stay fit and young.',
                'keywords_en' => 'activ world, health, personal care, fit, young',
                'url_img' => '',
                'color' => NULL,
                'created_at' => '2019-04-23 12:47:57',
                'updated_at' => '2019-04-23 12:48:31',
            ),
            8 => 
            array (
                'id' => 9,
                'enable' => 1,
                'icon' => '',
                'url_name_es' => 'hogar',
                'name_es' => 'Hogar',
                'title_es' => 'Home PagoSpot',
                'description_es' => 'Artículos para equipar, decorar, alegrar o completar tu hogar, muebles, lencerías, vajillas, lámparas, electrodomésticos y demás para tu casa.',
                'keywords_es' => 'hogar, artículos, equipar, muebles, lencería, decorar, vajillas, decorar',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_name_en' => 'home',
                'name_en' => 'Home',
                'title_en' => 'Home PagoSpot',
                'description_en' => 'A place to find that item you are looking to equip, decorate your home, furniture, lingerie, dishes, lamps, appliances and other items for your home.',
                'keywords_en' => 'home, decorate, furniture, lingerie, dishes, lamps, appliances',
                'url_img' => '',
                'color' => NULL,
                'created_at' => '2019-04-23 12:47:57',
                'updated_at' => '2019-04-23 12:48:31',
            ),
            9 => 
            array (
                'id' => 10,
                'enable' => 1,
                'icon' => '',
                'url_name_es' => 'oficina',
                'name_es' => 'Oficina',
                'title_es' => 'oficina PagoSpot',
                'description_es' => 'Artículos, mobiliario, papelería, tintas, toner todo en un solo click y lugar desde la comodidad de tu dispositivo.',
                'keywords_es' => 'artículos, mobiliario, papelería',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_name_en' => 'office',
                'name_en' => 'Office',
                'title_en' => 'Office PagoSpot',
                'description_en' => 'In one click & spot find a solution in what you are looking for, office supplies, paper, ink, toner, and others from the comfort of your devices.',
                'keywords_en' => 'stationery, office supplies , paper, ink, toner',
                'url_img' => '',
                'color' => NULL,
                'created_at' => '2019-04-23 12:47:57',
                'updated_at' => '2019-04-23 12:48:31',
            ),
            10 => 
            array (
                'id' => 11,
                'enable' => 1,
                'icon' => '',
                'url_name_es' => 'tv-y-audio',
                'name_es' => 'Tv y Audio ',
                'title_es' => 'Tv y Audio ',
                'description_es' => 'Últimas novedades tecnológicas en Audio y Tv. PagoSpot te da la oportunidad proponer la oferta a tu medida.',
                'keywords_es' => ' Audio, Tv, tecnología, novedades tecnológicas.',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_name_en' => 'tv-audio',
                'name_en' => 'TV & Audio',
                'title_en' => 'TV & Audio',
                'description_en' => 'The latest technological developments in Audio & TV. PagoSpot gives you the opportunity to propose an offer.',
                'keywords_en' => 'latest, technological developments, audio, TV',
                'url_img' => '',
                'color' => NULL,
                'created_at' => '2019-04-23 12:47:57',
                'updated_at' => '2019-04-23 12:48:31',
            ),
            11 => 
            array (
                'id' => 12,
                'enable' => 1,
                'icon' => '',
                'url_name_es' => 'fotografia-y-video',
                'name_es' => 'Fotografia y Video',
                'title_es' => 'Fotografia y Video',
                'description_es' => 'Últimas novedades tecnológicas en fotografia y video. PagoSpot te da la oportunidad proponer la oferta a tu medida.',
                'keywords_es' => ' foto, fotografia, video, tecnología, novedades tecnológicas.',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_name_en' => 'photo-video',
                'name_en' => 'Photo & Video',
                'title_en' => 'Photo & Video',
                'description_en' => 'The latest technological developments in Photo & Video. PagoSpot gives you the opportunity to propose an offer.',
                'keywords_en' => 'latest, technological developments, photo, video',
                'url_img' => '',
                'color' => NULL,
                'created_at' => '2019-04-23 12:47:57',
                'updated_at' => '2019-04-23 12:48:31',
            ),
            12 => 
            array (
                'id' => 13,
                'enable' => 1,
                'icon' => '',
                'url_name_es' => 'celulares-y-telefonos',
                'name_es' => 'Celulares y Telefonos',
                'title_es' => 'Celulares y Tablets PagoSpot',
                'description_es' => 'Increibles ofertas en una gran variedad de marcas, modelos y accesorios para Celulares y Tablets de tu preferencia.',
                'keywords_es' => 'celulares, tablets, modelos, accesorios, marcas',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_name_en' => 'cellphones-phones',
                'name_en' => 'CellPhones & Phones',
                'title_en' => 'Phones & Tablets PagoSpot',
                'description_en' => 'Amazing deals and offers on a great selection of brands, models and accessories for your Cell Phone & Tablet 
',
                'keywords_en' => 'Phones, cell phones, accessories, models, brands, tablets',
                'url_img' => '',
                'color' => NULL,
                'created_at' => '2019-04-23 12:47:57',
                'updated_at' => '2019-04-23 12:48:31',
            ),
            13 => 
            array (
                'id' => 14,
                'enable' => 1,
                'icon' => '',
                'url_name_es' => 'computacion',
                'name_es' => 'Computación',
                'title_es' => 'Computación PagoSpot',
                'description_es' => 'Laptops, de escritorios, discos externos, memorias, monitores, routers, hardware, redes, teclados, tarjetas, PC gamers, accesorios, en un solo punto.',
                'keywords_es' => 'Laptops, computadores de escritorios, discos externos, memorias, monitores, routers, hardware, redes, teclados, tarjetas de video, PC gamers, accesorios',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_name_en' => 'computing',
                'name_en' => 'Computing',
                'title_en' => 'Computer PagoSpot',
                'description_en' => 'Laptops, desktop computers, drivers, memory`s, monitors, routers, hardware, networking, keyboards, cards, PC gamers, accessories. all in one Spot.',
                'keywords_en' => 'Laptops, desktop computers, drivers, memory, monitors, routers, hardware, networking, keyboards, video cards, PC gamers, accessories',
                'url_img' => '',
                'color' => NULL,
                'created_at' => '2019-04-23 12:47:57',
                'updated_at' => '2019-04-23 12:48:31',
            ),
            14 => 
            array (
                'id' => 15,
                'enable' => 1,
                'icon' => '',
                'url_name_es' => 'consolas-y-juegos-de-video',
                'name_es' => 'Consolas y Juegos de video',
                'title_es' => 'Consolas y Juegos de videos PagoSpot',
                'description_es' => 'PagoSpot trae para ti las mejores opciones de las últimas consolas de videojuegos PlayStation, XBox, Wii y sus novedades de juegos. ',
                'keywords_es' => 'consolas de videojuegos, PlayStation, XBox, Wii, juegos, tendencias, novedades de juegos',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_name_en' => 'consoles-videogames',
                'name_en' => 'Consoles & Videogames',
                'title_en' => 'Consoles & Videogames PagoSpot',
                'description_en' => 'PagoSpot brings you the best options of the latest consoles PlayStation, XBox, Wii games and new games. Stay update of the latest trends and news.',
                'keywords_en' => 'consoles, PlayStation, XBox, Wii, games, new, latest trends ',
                'url_img' => '',
                'color' => NULL,
                'created_at' => '2019-04-23 12:47:57',
                'updated_at' => '2019-04-23 12:48:31',
            ),
            15 => 
            array (
                'id' => 16,
                'enable' => 1,
                'icon' => '',
                'url_name_es' => 'deporte-y-outdoors',
                'name_es' => 'Deporte y Outdoors',
                'title_es' => 'Deporte y Outdoors PagoSpot',
                'description_es' => 'PagoSpot te ofrece los artículos que necesitas para tus actividades al aire libre, fitness, ciclismo, running y deportes en general.

',
                'keywords_es' => 'articulos, deportes, fitness, ciclismo, running, aire libre',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_name_en' => 'sports-outdoors',
                'name_en' => 'Sports & Outdoors',
                'title_en' => 'Sports & Outdoors PagoSpot',
                'description_en' => 'We are the best online Sports & Outdoors stores. Find the items you need for your outdoor activities, fitness, cycling, running and sports in general.',
                'keywords_en' => 'Sports, Outdoors, activities, fitness, cycling, running, general sports',
                'url_img' => '',
                'color' => NULL,
                'created_at' => '2019-04-23 12:47:57',
                'updated_at' => '2019-04-23 12:48:31',
            ),
            16 => 
            array (
                'id' => 17,
                'enable' => 1,
                'icon' => '',
                'url_name_es' => 'hobbies',
                'name_es' => 'Hobbies',
                'title_es' => '',
                'description_es' => '',
                'keywords_es' => '',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_name_en' => 'hobbies',
                'name_en' => 'Hobbies',
                'title_en' => '',
                'description_en' => '',
                'keywords_en' => '',
                'url_img' => '',
                'color' => NULL,
                'created_at' => '2019-04-23 12:47:57',
                'updated_at' => '2019-04-23 12:48:31',
            ),
            17 => 
            array (
                'id' => 18,
                'enable' => 1,
                'icon' => '',
                'url_name_es' => 'bebes',
                'name_es' => 'Bebes',
                'title_es' => 'Bebés',
                'description_es' => 'Todo para consentir a los pequeños, desde pañales, artículos de cuidado de la piel, artículos de baño, ropa, alimentación hasta juegos y juguetes.',
                'keywords_es' => 'pequeños, casa, pañales, cuidados, piel, baños, alimentación, juegos, juguetes.',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_name_en' => 'babys',
                'name_en' => 'Babys',
                'title_en' => 'Babys & Toys PagoSpot',
                'description_en' => 'For our little ones PagoSpot brings you the best products going from diapers, skin care, bath products, clothing, food to toys and games.',
                'keywords_en' => 'brands, competitive, diapers, bath products, food, toys, games, babies, little ones.',
                'url_img' => '',
                'color' => NULL,
                'created_at' => '2019-04-23 12:47:57',
                'updated_at' => '2019-04-23 12:48:31',
            ),
            18 => 
            array (
                'id' => 19,
                'enable' => 1,
                'icon' => '',
                'url_name_es' => 'juguetes',
                'name_es' => 'Juguetes',
                'title_es' => ' Juguetes',
                'description_es' => '',
                'keywords_es' => '',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_name_en' => 'toys',
                'name_en' => 'Toys',
                'title_en' => '',
                'description_en' => '',
                'keywords_en' => '',
                'url_img' => '',
                'color' => NULL,
                'created_at' => '2019-04-23 12:47:57',
                'updated_at' => '2019-04-23 12:48:31',
            ),
            19 => 
            array (
                'id' => 20,
                'enable' => 1,
                'icon' => '',
                'url_name_es' => 'musica',
                'name_es' => 'Musica',
                'title_es' => 'Musica',
                'description_es' => 'Últimas novedades tecnológicas en Audio y Tv. PagoSpot te da la oportunidad proponer la oferta a tu medida.',
                'keywords_es' => ' Audio, Tv, tecnología, novedades tecnológicas.',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_name_en' => 'musica',
                'name_en' => 'Musica',
                'title_en' => 'Musica',
                'description_en' => 'The latest technological developments in Audio & TV. PagoSpot gives you the opportunity to propose an offer.',
                'keywords_en' => 'latest, technological developments, audio, TV',
                'url_img' => '',
                'color' => NULL,
                'created_at' => '2019-04-23 12:47:57',
                'updated_at' => '2019-04-23 12:48:31',
            ),
            20 => 
            array (
                'id' => 21,
                'enable' => 1,
                'icon' => '',
                'url_name_es' => 'mascotas',
                'name_es' => 'Mascotas',
                'title_es' => 'Mascotas PagoSpot',
                'description_es' => 'Para tus mascotas alimentos, juguetes, medicinas, accesorios, servicios de peluquería y veterinaria para perros, gatos, aves, y demás animalitos.',
                'keywords_es' => 'alimentos, juguetes, medicinas, accesorios, peluquería, veterinaria, perros, gatos, aves, reptiles, roedores, animalitos',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_name_en' => 'pets',
                'name_en' => 'Pets',
                'title_en' => 'Pets PagoSpot',
                'description_en' => 'For your pets. food, toys, medicines, accessories, hairdressing and veterinary services for dogs, cats, birds, reptiles, rodents and other animals.',
                'keywords_en' => 'food, toys, medicines, accessories, hairdressing, veterinary, dogs,cats,birds, reptiles, rodents, animals',
                'url_img' => '',
                'color' => NULL,
                'created_at' => '2019-04-23 12:47:57',
                'updated_at' => '2019-04-23 12:48:31',
            ),
            21 => 
            array (
                'id' => 22,
                'enable' => 1,
                'icon' => '',
                'url_name_es' => 'supermercado',
                'name_es' => 'Supermercado',
                'title_es' => 'Supermercado PagoSpot',
                'description_es' => 'No alcanzas a ir al super? tus compras nunca fueron tan sencillas, seguras y divertidas, ven y descubre la forma de comprar en el futuro ahora.',
                'keywords_es' => 'sencillas, seguras y divertidas, comprar, super, descubre, forma',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_name_en' => 'supermarket',
                'name_en' => 'Supermarket',
                'title_en' => 'Supermarket PagoSpot',
                'description_en' => 'Don`t reach the time to go to the supermarket ? Your purchases have never been so easy, safe and fun, discover how to buy on a future way now.',
                'keywords_en' => 'supermarket, easy,safe, fun, confort, device',
                'url_img' => '',
                'color' => NULL,
                'created_at' => '2019-04-23 12:47:57',
                'updated_at' => '2019-04-23 12:48:31',
            ),
            22 => 
            array (
                'id' => 23,
                'enable' => 1,
                'icon' => '',
                'url_name_es' => 'ferreteria-y-construccion-liviana',
                'name_es' => 'Ferreteria y Construcción Liviana',
                'title_es' => 'Todo lo que necesitas para arreglos en tu casa o constricion',
                'description_es' => 'Todo lo que necesitas para arreglos en tu casa o constricion',
                'keywords_es' => 'ferreteria, construccion',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_name_en' => 'ferreteria-y-construccion-liviana',
                'name_en' => 'Ferreteria y Construcción Liviana',
                'title_en' => 'Todo lo que necesitas para arreglos en tu casa o constricion',
                'description_en' => 'Todo lo que necesitas para arreglos en tu casa o constricion',
                'keywords_en' => 'ferreteria, construccion',
                'url_img' => '',
                'color' => NULL,
                'created_at' => '2019-04-23 12:47:57',
                'updated_at' => '2019-04-23 12:48:31',
            ),
            23 => 
            array (
                'id' => 24,
                'enable' => 1,
                'icon' => '',
                'url_name_es' => 'automoviles',
                'name_es' => 'Automoviles',
                'title_es' => 'automóviles PagoSpot',
                'description_es' => 'Te brindamos una serie de tiendas y productos para carro. Accesorios, tuning, repuestos, forros, seguros y todo lo que necesites para tu vehículo.',
                'keywords_es' => 'automóvil, accesorios, tuning, repuestos, forros, seguros, vehículo, carro',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_name_en' => 'automotive',
                'name_en' => 'Automotive',
                'title_en' => 'Automotive PagoSpot',
                'description_en' => 'We provide a number of stores and products with accessories, tuning, spare parts, covers, insurance and everything you need for your vehicle.',
                'keywords_en' => 'accessories, tuning, spare parts, covers, insurance, vehicle, car',
                'url_img' => '',
                'color' => NULL,
                'created_at' => '2019-04-23 12:47:57',
                'updated_at' => '2019-04-23 12:48:31',
            ),
            24 => 
            array (
                'id' => 25,
                'enable' => 1,
                'icon' => '',
                'url_name_es' => 'viajes',
                'name_es' => 'Viajes',
                'title_es' => 'Viajes PagoSpot',
                'description_es' => 'A que destino quieres ir, en PagoSpot.com encuntra las mejores ofertas y realiza estos viajes desdeados de vacaciones o negocios.',
                'keywords_es' => 'destino, viajes, vacasiones, negocios, ofertas',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_name_en' => 'travel',
                'name_en' => 'Travel',
                'title_en' => 'Travel PagoSpot',
                'description_en' => 'Already know the destination that you want to go in PagoSpot.com find the best deals and make these desired trips for vacation or business.',
                'keywords_en' => 'destinations, trips, vacations, business, travel, deals',
                'url_img' => '',
                'color' => NULL,
                'created_at' => '2019-04-23 12:47:57',
                'updated_at' => '2019-04-23 12:48:31',
            ),
            25 => 
            array (
                'id' => 26,
                'enable' => 1,
                'icon' => '',
                'url_name_es' => 'promociones',
                'name_es' => 'Promociones',
                'title_es' => 'Promociones PagoSpot',
                'description_es' => 'El mejor sitio para conseguir y ofertar los productos y servicios. Crea tu tienda y descubre una manera fácil y divertida de hacer negocios.',
                'keywords_es' => 'siti, ofertar, productos, servicios, descubre, negocios, manera, fácil',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_name_en' => 'offers',
                'name_en' => 'Offers',
                'title_en' => 'Offers PagoSpot',
                'description_en' => 'PagoSpot the newest place to get and offer products & services of your interest. Create your store and discover a new easy and fun way to do business.',
                'keywords_en' => 'newest, place, offer, products, services, store, discover, business',
                'url_img' => '',
                'color' => NULL,
                'created_at' => '2019-04-23 12:47:57',
                'updated_at' => '2019-04-23 12:48:31',
            ),
            26 => 
            array (
                'id' => 27,
                'enable' => 1,
                'icon' => '',
                'url_name_es' => 'pagospot-varios',
                'name_es' => 'PagoSpot Varios',
                'title_es' => 'Varios PagoSpot',
                'description_es' => 'Todo lo que quieras vender o comprar, ven y crea tu solución de negocio.',
                'keywords_es' => 'Varios, artículos, crea, solución, negocio, vender, comprar',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_name_en' => 'pagospot-others',
                'name_en' => 'PagoSpot others',
                'title_en' => 'Others PagoSpot ',
                'description_en' => 'All you want to buy and offer. Come and create your business solution.',
                'keywords_en' => 'Products, others, create, business, solution, offer, buy',
                'url_img' => '',
                'color' => NULL,
                'created_at' => '2019-04-23 12:47:57',
                'updated_at' => '2019-04-23 12:48:31',
            ),
        ));
        
        
    }
}