<?php

use Illuminate\Database\Seeder;

class CgDepartamentsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        DB::table('cg_departaments')->delete();

        DB::table('cg_departaments')->insert(array(
            0 =>
            array(
                'id' => 1,
                'enable' => 1,
                'icon' => 'fas fa-th-large',
                'url_name_es' => 'mujer',
                'name_es' => 'Mujer',
                'title_es' => 'Mujer',
                'description_es' => 'Todo en moda, accesorios, cuidado personal y mas para mujeres.',
                'keywords_es' => 'Mujer,moda,abrigos,chaquetas,pantalones,jean,novias,embarazadas,calzado,relojes,gafas,lentes,moda,trendy,cuidado,personal,perfumes,joyeria,bolsos,DeComprita',
                'name_en' => 'Women',
                'url_name_en' => 'women',
                'title_en' => 'Women',
                'description_en' => 'Everything in fashion, accessories, personal care and more for women.',
                'keywords_en' => 'Women,fashion,wraps,coats,trousers,jean,footwear,watches,glasses,glasses,fashion,trendy,care,personal,perfumes,jewelry,bags,DeComprita',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_img' => '',
                'color' => '#34F56B',
                'created_at' => '2019-01-01 12:00:00',
                'updated_at' => '2019-01-01 12:00:00'
            ),
            1 =>
            array(
                'id' => 2,
                'enable' => 1,
                'icon' => 'fas fa-th-large',
                'url_name_es' => 'hombres',
                'name_es' => 'Hombres',
                'title_es' => 'Hombres',
                'description_es' => 'Todo en moda, accesorios, cuidado personal y mas para hombres.',
                'keywords_es' => 'hombre,moda,abrigos,chaquetas,pantalones,jean,novios,calzado,relojes,gafas,lentes,moda,trendy,cuidado,personal,perfumes,joyeria,bolsos,DeComprita',
                'name_en' => 'Men',
                'url_name_en' => 'men',
                'title_en' => 'Men',
                'description_en' => 'Everything in fashion, accessories, personal care and more for men.',
                'keywords_en' => 'man,fashion,coats,coats,trousers,jean,boyfriend,footwear,watches,glasses,eyeglasses,fashion,trendy,care,personal,perfumes,jewelry,bags,DeComprita',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_img' => '',
                'color' => '#34F56B',
                'created_at' => '2019-01-01 12:00:00',
                'updated_at' => '2019-01-01 12:00:00'
            ),
            2 =>
            array(
                'id' => 3,
                'enable' => 1,
                'icon' => 'fas fa-th-large',
                'url_name_es' => 'ninos',
                'name_es' => 'Niños ',
                'title_es' => 'Niños ',
                'description_es' => 'Todo en ropa, zapatos y más, para niños.',
                'keywords_es' => 'Abrigos,Chaqueta,Calzado,camisas,Pantalones,Ropa Interior,Trajes,Baño,Conjuntos,Escuela,Disfraces,moda,marca,DeComprita',
                'name_en' => 'Boys',
                'url_name_en' => 'boys',
                'title_en' => 'Boys',
                'description_en' => 'Everything in clothes, shoes and more, for children.',
                'keywords_en' => 'Coats, Jacket, Footwear, Shirts, Trousers, Underwear, Suits, Bath, Sets, School, Costumes, fashion, make, DeComprita',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_img' => '',
                'color' => '#34F56B',
                'created_at' => '2019-01-01 12:00:00',
                'updated_at' => '2019-01-01 12:00:00'
            ),
            3 =>
            array(
                'id' => 4,
                'enable' => 1,
                'icon' => 'fas fa-th-large',
                'url_name_es' => 'ninas',
                'name_es' => 'Niñas',
                'title_es' => 'Niñas',
                'description_es' => 'Todo en ropa, calzado y más, para niñas.',
                'keywords_es' => 'Abrigos,Chaqueta,Calzado,camisas,Pantalones,Ropa Interior,Trajes,niñas,Baño,Conjuntos,Escuela,Disfraces,moda,marca,DeComprita',
                'name_en' => 'Girls',
                'url_name_en' => 'girls',
                'title_en' => 'Girls',
                'description_en' => 'All in clothes, shoes and more, for girls.',
                'keywords_en' => 'Coats, Jacket, Footwear, Shirts, Trousers, Underwear, Suits, Bath, Sets, School, Costumes, fashion, make, buy,DeComprita',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_img' => '',
                'color' => '#34F56B',
                'created_at' => '2019-01-01 12:00:00',
                'updated_at' => '2019-01-01 12:00:00'
            ),
            4 =>
            array(
                'id' => 5,
                'enable' => 1,
                'icon' => 'fas fa-th-large',
                'url_name_es' => 'hogar',
                'name_es' => 'Hogar',
                'title_es' => 'Hogar',
                'description_es' => 'Todo en artículos decorativos, Electrodomésticos, muebles y más para tu hogar.',
                'keywords_es' => 'Cocina,Tocador,Sala,comedor,Recamara,Jardin,Exterior,Electrodomesticos,Decoracion,hogar,DeComprita',
                'name_en' => 'Home',
                'url_name_en' => 'home',
                'title_en' => 'Home',
                'description_en' => 'Everything in decorative items, appliances, furniture and more for your home.',
                'keywords_en' => 'Kitchen, Dressing Room, Living Room, Bedroom, Bedroom, Garden, Exterior, Appliances, Decoration, Home, DeComprita',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_img' => '',
                'color' => '#34F56B',
                'created_at' => '2019-01-01 12:00:00',
                'updated_at' => '2019-01-01 12:00:00'
            ),
            5 =>
            array(
                'id' => 6,
                'enable' => 1,
                'icon' => 'fas fa-th-large',
                'url_name_es' => 'oficina',
                'name_es' => 'Oficina',
                'title_es' => 'Oficina',
                'description_es' => 'Todo en artículos para la oficina.',
                'keywords_es' => 'Equipos,Oficina,Impresoras,Fotocopiadoras,Materiales,articulos,DeComprita',
                'name_en' => 'Office',
                'url_name_en' => 'office',
                'title_en' => 'Office',
                'description_en' => 'Everything in articles for the office.',
                'keywords_en' => 'Equipment,Office,Printers,Photocopiers,Materials,Supplies,Decomprita',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_img' => '',
                'color' => '#34F56B',
                'created_at' => '2019-01-01 12:00:00',
                'updated_at' => '2019-01-01 12:00:00'
            ),
            6 =>
            array(
                'id' => 7,
                'enable' => 1,
                'icon' => 'fas fa-th-large',
                'url_name_es' => 'imagen-y-audio',
                'name_es' => 'Imagen y Audio',
                'title_es' => 'Imagen y Audio',
                'description_es' => 'Todo en artículos y modelos de televisores, equipos de sonido, vídeo beam y más, de tus marcas favoritas. tv,audio,imagen,televisor,equipo,sonido,accesorios,video,beam,marcas,DeComprita',
                'keywords_es' => 'tv,audio,imagen,televisor,equipo,sonido,accesorios,video,beam,marcas,DeComprita',
                'name_en' => 'Image and Audio',
                'url_name_en' => 'image-and-audio',
                'title_en' => 'Image and Audio',
                'description_en' => 'Everything in articles and models of televisions, sound equipment, video beam and more, of your favorite brands.',
                'keywords_en' => 'tv, audio, image, television, equipment, sound, accessories, video, beam, marks, Depr',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_img' => '',
                'color' => '#34F56B',
                'created_at' => '2019-01-01 12:00:00',
                'updated_at' => '2019-01-01 12:00:00'
            ),
            7 =>
            array(
                'id' => 8,
                'enable' => 1,
                'icon' => 'fas fa-th-large',
                'url_name_es' => 'fotografia-y-video',
                'name_es' => 'Fotografía y Vídeo',
                'title_es' => 'Fotografía y Vídeo',
                'description_es' => 'Todo en modelos, accesorios y marcas de cámaras y vídeo grabadoras. fotogradia,video,grabadora,camara,profesional,accesorios,DeComprita',
                'keywords_es' => 'fotogradia,video,grabadora,camara,profesional,accesorios,DeComprita',
                'name_en' => 'image and photo',
                'url_name_en' => 'image-and-photo',
                'title_en' => 'image and photo',
                'description_en' => 'Everything in models, accessories and brands of cameras and video recorders.',
                'keywords_en' => 'photographe, video, recorder, camera, professional, accessories, DeComprita',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_img' => '',
                'color' => '#34F56B',
                'created_at' => '2019-01-01 12:00:00',
                'updated_at' => '2019-01-01 12:00:00'
            ),
            8 =>
            array(
                'id' => 9,
                'enable' => 1,
                'icon' => 'fas fa-th-large',
                'url_name_es' => 'celulares',
                'name_es' => 'Celulares',
                'title_es' => 'Celulares',
                'description_es' => 'Todo en accesorios y marcas de dispositivos móviles y fijos, de tus marcas favoritas. celulares,smartphone,celular,dospositivo,movil,fijo,marcas,DeComprira',
                'keywords_es' => 'celulares,smartphone,celular,dospositivo,movil,fijo,marcas,DeComprira',
                'name_en' => 'Phone',
                'url_name_en' => 'phone',
                'title_en' => 'Phone',
                'description_en' => 'All in accessories and brands of mobile and fixed devices, your favorite brands.',
                'keywords_en' => 'cellular, smartphone, cellular, device, mobile, fixed, marks, DeComprita',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_img' => '',
                'color' => '#34F56B',
                'created_at' => '2019-01-01 12:00:00',
                'updated_at' => '2019-01-01 12:00:00'
            ),
            9 =>
            array(
                'id' => 10,
                'enable' => 1,
                'icon' => 'fas fa-th-large',
                'url_name_es' => 'computacion',
                'name_es' => 'Computación',
                'title_es' => 'Computación',
                'description_es' => 'Todo en computadoras, los modelos mas recientes de tus marcas favoritas. Computadora,lapto,equipo,trabajo,lapto,tablet,accesorio,monitor,estudio,pc,escritorio,portatil,DeComprita',
                'keywords_es' => 'Computadora,lapto,equipo,trabajo,lapto,tablet,accesorio,monitor,estudio,pc,escritorio,portatil,DeComprita',
                'name_en' => 'Computing',
                'url_name_en' => 'computing',
                'title_en' => 'Computing',
                'description_en' => 'Everything on computers, the latest models of your favorite brands.',
                'keywords_en' => 'Computer, lapto, computer, work, lapto, tablet, accessory, monitor, studio, pc, desktop, laptop, DeComprita',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_img' => '',
                'color' => '#34F56B',
                'created_at' => '2019-01-01 12:00:00',
                'updated_at' => '2019-01-01 12:00:00'
            ),
            10 =>
            array(
                'id' => 11,
                'enable' => 1,
                'icon' => 'fas fa-th-large',
                'url_name_es' => 'videogames',
                'name_es' => 'Videogames',
                'title_es' => 'Videogames',
                'description_es' => 'Gran variedad en juegos de vídeo, consolas de todas las marcas, accesorios y más.',
                'keywords_es' => 'consola,video,juegos,de,consola,fijas,portatiles,entretenimiento,adaptador,control,controlador,conector,DeComprita',
                'name_en' => 'Videogames',
                'url_name_en' => 'videogames',
                'title_en' => 'Videogames',
                'description_en' => 'Great variety in video games, consoles of all brands, accessories and more.',
                'keywords_en' => 'console, video, games, console, fixed, portable, entertainment, adapter, control, controller, connector, DeComprita',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_img' => '',
                'color' => '#34F56B',
                'created_at' => '2019-01-01 12:00:00',
                'updated_at' => '2019-01-01 12:00:00'
            ),
            11 =>
            array(
                'id' => 12,
                'enable' => 1,
                'icon' => 'fas fa-th-large',
                'url_name_es' => 'deportes-y-outdoors',
                'name_es' => 'Deportes y Outdoors',
                'title_es' => 'Deportes y Outdoors',
                'description_es' => 'Todo en artículos para deportes y actividades al aire libre. deporte,outdoor,accesorio,tenis,futbol,baloncesto,basquet,acuaticos,herramientas,tenias,golf,campamento,aventura,ciclismo,DeComprita',
                'keywords_es' => 'deporte,outdoor,accesorio,tenis,futbol,baloncesto,basquet,acuaticos,herramientas,tenias,golf,campamento,aventura,ciclismo,DeComprita',
                'name_en' => 'Sport and outdoors',
                'url_name_en' => 'sport-and-outdoors',
                'title_en' => 'Sport and outdoors',
                'description_en' => 'All in articles for sports and outdoor activities.',
                'keywords_en' => 'sport, outdoor, accessory, tennis, soccer, basketball, basketball, water, tools, tapeworms, golf, camp, adventure, cycling, DeComprita',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_img' => '',
                'color' => '#34F56B',
                'created_at' => '2019-01-01 12:00:00',
                'updated_at' => '2019-01-01 12:00:00'
            ),
            12 =>
            array(
                'id' => 13,
                'enable' => 1,
                'icon' => 'fas fa-th-large',
                'url_name_es' => 'bebes',
                'name_es' => 'Bebés',
                'title_es' => 'Bebés',
                'description_es' => 'Variedad en artículos de decoraciones, moda y más, para tus bebés.',
                'keywords_es' => 'bebes,Moda,Decoraciones,Recuerdos,Seguridad,Porta,Bebe,DeComprita',
                'name_en' => 'Baby',
                'url_name_en' => 'baby',
                'title_en' => 'Baby',
                'description_en' => 'Variety in articles of decorations, fashion and more, for your babies.',
                'keywords_en' => 'babies, fashion, decorations, keepsakes, security, door, baby, shop, DeComprita',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_img' => '',
                'color' => '#34F56B',
                'created_at' => '2019-01-01 12:00:00',
                'updated_at' => '2019-01-01 12:00:00'
            ),
            13 =>
            array(
                'id' => 14,
                'enable' => 1,
                'icon' => 'fas fa-th-large',
                'url_name_es' => 'juguetes',
                'name_es' => 'Juguetes ',
                'title_es' => 'Juguetes ',
                'description_es' => 'Gran variedad en modelos y marcas de juguetes, con los mejores precios. juguetes,juegos,bloques,construccion,niños,niñas,Muñecos,Figuras,Accion,Juguetes,variados,Mesa,aire,Libre,DeComprita',
                'keywords_es' => 'juguetes,juegos,bloques,construccion,niños,niñas,Muñecos,Figuras,Accion,Juguetes,variados,Mesa,aire,Libre,DeComprita',
                'name_en' => 'Toys',
                'url_name_en' => 'toys',
                'title_en' => 'Toys',
                'description_en' => 'Great variety in models and brands of toys, with the best prices.',
                'keywords_en' => 'toys, games, blocks, construction, children, girls, dolls, figures, action, toys, assorted, table, air, free, buy, DeComprita',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_img' => '',
                'color' => '#34F56B',
                'created_at' => '2019-01-01 12:00:00',
                'updated_at' => '2019-01-01 12:00:00'
            ),
            14 =>
            array(
                'id' => 15,
                'enable' => 1,
                'icon' => 'fas fa-th-large',
                'url_name_es' => 'musica',
                'name_es' => 'Música ',
                'title_es' => 'Música ',
                'description_es' => 'Todo en modelos y marcas de instrumentos de música, accesorios y más. musica,grabacion,sets,grabador,edicion,equipos,instrumentos,bajis,guitarras,tambores,guitarra,electrica,DeComprita',
                'keywords_es' => 'musica,grabacion,sets,grabador,edicion,equipos,instrumentos,bajis,guitarras,tambores,guitarra,electrica,DeComprita',
                'name_en' => 'Music',
                'url_name_en' => 'music',
                'title_en' => 'Music',
                'description_en' => 'All in models and brands of musical instruments, accessories and more.',
                'keywords_en' => 'music, recording, sets, recorder, editing, equipment, instruments, bajis, guitars, drums, guitar, electric, DeComprita',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_img' => '',
                'color' => '#34F56B',
                'created_at' => '2019-01-01 12:00:00',
                'updated_at' => '2019-01-01 12:00:00'
            ),
            15 =>
            array(
                'id' => 16,
                'enable' => 1,
                'icon' => 'fas fa-th-large',
                'url_name_es' => 'supermercado',
                'name_es' => 'Supermercado',
                'title_es' => 'Supermercado',
                'description_es' => 'Gran variedad en productos y marcas de bebidas, alimentos y más. supermercado,comida,bebidas,alimentos,limpieza,productos,hogar,vegetales,carnes,bebidas,DeComprita',
                'keywords_es' => 'supermercado,comida,bebidas,alimentos,limpieza,productos,hogar,vegetales,carnes,bebidas,DeComprita',
                'name_en' => 'supermarket',
                'url_name_en' => 'supermarket',
                'title_en' => 'supermarket',
                'description_en' => 'Great variety in products and brands of drinks, food and more.',
                'keywords_en' => 'supermarket, food, drinks, food, cleaning, products, home, vegetables, meats, beverages, DeComprita',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_img' => '',
                'color' => '#34F56B',
                'created_at' => '2019-01-01 12:00:00',
                'updated_at' => '2019-01-01 12:00:00'
            ),
            16 =>
            array(
                'id' => 17,
                'enable' => 1,
                'icon' => 'fas fa-th-large',
                'url_name_es' => 'ferreteria-y-construccion-liviana',
                'name_es' => 'Ferretería y Construcción Liviana ',
                'title_es' => 'Ferretería y Construcción Liviana ',
                'description_es' => 'Todo en equipos de ferretería y construcción. Ferreteria,construccion,liviana,herramientas,manuales,electricas,equipo,seguridad,griferia,tuberia,DeComprita Ferretería y Construcción Liviana ',
                'keywords_es' => 'Ferreteria,construccion,liviana,herramientas,manuales,electricas,equipo,seguridad,griferia,tuberia,DeComprita',
                'name_en' => 'Hardware and Light Construction',
                'url_name_en' => 'hardware-and-light-construction',
                'title_en' => 'Hardware and Light Construction',
                'description_en' => 'Everything in hardware and construction equipment.',
                'keywords_en' => 'Hardware, construction, light, tools, manuals, electrical, equipment, safety, faucet, piping, DeComprita',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_img' => '',
                'color' => '#34F56B',
                'created_at' => '2019-01-01 12:00:00',
                'updated_at' => '2019-01-01 12:00:00'
            ),
            17 =>
            array(
                'id' => 18,
                'enable' => 1,
                'icon' => 'fas fa-th-large',
                'url_name_es' => 'food-courts',
                'name_es' => 'Food Courts',
                'title_es' => 'Food Courts',
                'description_es' => 'Gran variedad en platillos y comidas. food,courts,Comida,rapida,Gourmet,Bebidas,pizza,haburguesa,hod,dog,china,sushi,torta,helado,dulces,DeComprita ',
                'keywords_es' => 'food,courts,Comida,rapida,Gourmet,Bebidas,pizza,haburguesa,hot,dog,china,sushi,torta,helado,dulces,DeComprita ',
                'name_en' => 'food courts',
                'url_name_en' => 'food-courts',
                'title_en' => 'food courts',
                'description_en' => 'Great variety in dishes and meals. food courts food fast gourmet gourmet drinks pizza haburguesa hod dog china sushi cake ice cream confectionery',
                'keywords_en' => 'food,courts,fast,gourmet,drinks,pizza,burger,hot,dog,china,sushi,cake,ice,cream,confectionery,DeComprita',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_img' => '',
                'color' => '#34F56B',
                'created_at' => '2019-01-01 12:00:00',
                'updated_at' => '2019-01-01 12:00:00'
            ),
            18 =>
            array(
                'id' => 19,
                'enable' => 1,
                'icon' => 'fas fa-th-large',
                'url_name_es' => 'electronica',
                'name_es' => 'Electrónica  ',
                'title_es' => 'Electrónica  ',
                'description_es' => 'Encuentra aquí todo en equipo de electrónica. Electronica,Micros,Modulos,3D,CNC,Display,Sensores,Comunicación,Electronica,Drivers,motores,Kits,robots,DeComprita',
                'keywords_es' => 'Electronica,Micros,Modulos,3D,CNC,Display,Sensores,Comunicación,Electronica,Drivers,motores,Kits,robots,DeComprita',
                'name_en' => 'Electronic',
                'url_name_en' => 'electronic',
                'title_en' => 'Electronic',
                'description_en' => 'Find everything here in electronics equipment.',
                'keywords_en' => 'Electronic, Micros, Modules, 3D, CNC, Display, Sensors, Communication, Electronica, Drivers, Motors, Kits, Robots, Decomprita',
                'url_name_pt' => '',
                'name_pt' => '',
                'title_pt' => '',
                'description_pt' => '',
                'keywords_pt' => '',
                'url_img' => '',
                'color' => '#34F56B',
                'created_at' => '2019-01-01 12:00:00',
                'updated_at' => '2019-01-01 12:00:00'
            ),
        ));
    }
}
